INSERT INTO SOURCE_CENTER_ENGINE
SELECT nextval('S_SOURCE_CENTER_ENGINE_PK'), SC_ID, 'FINAM_APAC', GET_CG_ID_FROM_NAME('REGION', 'APAC'), NULL, NOW(), 'Y'
FROM SOURCE_CENTER
WHERE NAME = 'FINAM';

INSERT INTO SOURCE_CENTER_ENGINE
SELECT nextval('S_SOURCE_CENTER_ENGINE_PK'), SC_ID, 'FINAM_EMEA', GET_CG_ID_FROM_NAME('REGION', 'EMEA'), NULL, NOW(), 'Y'
FROM SOURCE_CENTER
WHERE NAME = 'FINAM';

INSERT INTO SOURCE_CENTER_ENGINE
SELECT nextval('S_SOURCE_CENTER_ENGINE_PK'), SC_ID, 'FINAM_NAM', GET_CG_ID_FROM_NAME('REGION', 'NAM'), NULL, NOW(), 'Y'
FROM SOURCE_CENTER
WHERE NAME = 'FINAM';

INSERT INTO SOURCE_CENTER_ENGINE
SELECT nextval('S_SOURCE_CENTER_ENGINE_PK'), SC_ID, 'YAHOO_APAC', GET_CG_ID_FROM_NAME('REGION', 'APAC'), NULL, NOW(), 'Y'
FROM SOURCE_CENTER
WHERE NAME = 'YAHOO';

INSERT INTO SOURCE_CENTER_ENGINE
SELECT nextval('S_SOURCE_CENTER_ENGINE_PK'), SC_ID, 'YAHOO_EMEA', GET_CG_ID_FROM_NAME('REGION', 'EMEA'), NULL, NOW(), 'Y'
FROM SOURCE_CENTER
WHERE NAME = 'YAHOO';

INSERT INTO SOURCE_CENTER_ENGINE
SELECT nextval('S_SOURCE_CENTER_ENGINE_PK'), SC_ID, 'YAHOO_NAM', GET_CG_ID_FROM_NAME('REGION', 'NAM'), NULL, NOW(), 'Y'
FROM SOURCE_CENTER
WHERE NAME = 'YAHOO';