@startuml

object SYSTEM_VARIABLE {
  NAME
  VALUE
}

object CODE_GENERIC {
  CG_ID
  TYPE
  NAME
  DESCRIPTION
  ACTIVE_FLAG
}

object SOURCE_CENTER {
  SC_ID
  NAME
  DESCRIPTION
  LAST_UPDATE_TM
  ACTIVE_FLAG
}

object SOURCE_CENTER_ENGINE {
  SCE_ID
  SC_ID
  NAME
  REGION_CG_ID
  CURRENT_COB_SCEI
  LAST_UPDATE_TM
  ACTIVE_FLAG
}

SOURCE_CENTER o-- SOURCE_CENTER_ENGINE: SC_ID
CODE_GENERIC o-- SOURCE_CENTER_ENGINE: REGION_CG_ID

object SOURCE_CENTER_ENGINE_INSTANCE {
  SCEI_ID
  SCE_ID
  BUSINESS_DATE
  SCEI_STATE_CG_ID
  SCEI_DETAIL_STATE_CD_ID
  START_TM
  END_TM
}

SOURCE_CENTER_ENGINE o-- SOURCE_CENTER_ENGINE_INSTANCE: SCE_ID
CODE_GENERIC o-- SOURCE_CENTER_ENGINE_INSTANCE: SCEI_STATE_CG_ID

object STAGE_FINAM_HISTORICAL {
  SFH_ID
  HASH
  SYMBOL
  PER
  DATE
  TIME
  OPEN
  HIGH
  LOW
  CLOSE
  VOLUME
  ACTIVE_FLAG
  ACTIVE_REASON
}

object STAGE_YAHOO_HISTORICAL {
  SFH_ID
  HASH
  SYMBOL
  PER
  DATE
  TIME
  OPEN
  HIGH
  LOW
  CLOSE
  VOLUME
  ACTIVE_FLAG
  ACTIVE_REASON
}

object SNAPSHOT_HISTORICAL {
  SH_ID
  SCEI_ID
  BUSINESS_DATE
  SYMBOL
  PER
  DATE
  TIME
  OPEN
  HIGH
  LOW
  CLOSE
  VOLUME
  ACTIVE_FLAG
}

SOURCE_CENTER_ENGINE_INSTANCE o-- SNAPSHOT_HISTORICAL: SCEI_ID
STAGE_FINAM_HISTORICAL <-- SNAPSHOT_HISTORICAL
STAGE_YAHOO_HISTORICAL <-- SNAPSHOT_HISTORICAL

@enduml