CREATE TABLE EXCHANGE (
    EX_ID               NUMERIC(18) NOT NULL,
    NAME                VARCHAR(20) NOT NULL,
    DESCRIPTION         VARCHAR(40) NOT NULL,
    COUNTY              VARCHAR(20) NOT NULL,
    REGION_CG_ID        NUMERIC(18) NOT NULL,
    TIMEZONE_UTC_DIF    NUMERIC(2) NOT NULL,
    LAST_UPDATE_TM      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT IPK_EXCHANGE PRIMARY KEY (EX_ID) DEFAULT nextval('S_EXCHANGE_PK')

) TABLESPACE GENERAL_INDEX;


ALTER TABLE EXCHANGE ADD CONSTRAINT IFK_CODE_GENERIC FOREIGN KEY (REGION_CG_ID) REFERENCES CODE_GENERIC (CG_ID) MATCH FULL;