CREATE TABLE SNAPSHOT_HISTORICAL (
                             SCEI_ID         NUMERIC(18) NOT NULL,
                             BUSINESS_DATE   DATETIME NOT NULL,
                             SYM_ID          NUMERIC(18) NOT NULL,
                             PER             DATETIME NOT NULL,
                             DATE            DATETIME NOT NULL,
                             TIME            DATETIME NOT NULL,
                             OPEN            NUMERIC(18) NOT NULL,
                             HIGH            NUMERIC(18) NOT NULL,
                             LOW             NUMERIC(18) NOT NULL,
                             CLOSE           NUMERIC(18) NOT NULL,
                             VOLUME          NUMERIC(18) NOT NULL,
                             ACTIVE_FLAG     CHAR(1) DEFAULT 'Y' NOT NULL,

CONSTRAINT IPK_SNAPSHOT_HISTORICAL PRIMARY KEY (SCEI_ID) DEFAULT nextval('S_SNAPSHOT_HISTORICAL_PK')
                           ) TABLESPACE GENERAL_INDEX;
ALTER TABLE SNAPSHOT_HISTORICAL ADD ( CHECK (ACTIVE_FLAG in ('Y','N') );
ALTER TABLE SNAPSHOT_HISTORICAL ADD CONSTRAINT IFK_SOURCE_CENTER_ENGINE_INSTANCE FOREIGN KEY (SCEI_ID) REFERENCES SOURCE_CENTER_ENGINE_INSTANCE (SCEI_ID) MATCH FULL;
ALTER TABLE SNAPSHOT_HISTORICAL ADD CONSTRAINT IFK_STAGE_FINAM_HISTORICAL FOREIGN KEY (SYM_ID) REFERENCES STAGE_FINAM_HISTORICAL (SYM_ID) MATCH FULL;
ALTER TABLE SNAPSHOT_HISTORICAL ADD CONSTRAINT IFK_STAGE_YAHOO_HISTORICAL FOREIGN KEY (SYM_ID) REFERENCES STAGE_YAHOO_HISTORICAL (SYM_ID) MATCH FULL;

