CREATE TABLE SNAPSHOT_QUOTE (
     SQ_ID                    NUMERIC(18) NOT NULL DEFAULT nextval('S_SNAPSHOT_QUOTE_PK'),
     SCEI_ID                  NUMERIC(18) NOT NULL,
     BUSINESS_DATE            DATE NOT NULL,
     SYM_ID                   NUMERIC(18) NOT NULL,
     AVG_DAILY_VOLUME         NUMERIC(18,2) NOT NULL,
     CHANGE                   NUMERIC(18,2) NOT NULL,
     DAYS_LOW                 NUMERIC(18,2) NOT NULL,
     DAYS_HIGH                NUMERIC(18,2) NOT NULL,
     YEAR_LOW                 NUMERIC(18,2) NOT NULL,
     YEAR_HIGH                NUMERIC(18,2) NOT NULL,
     MARKET_CAPITALIZATION    NUMERIC(18,2) NOT NULL,
     LAST_TRADE_PRICE         NUMERIC(18,2) NOT NULL,
     DAYS_RANGE_FROM          NUMERIC(18,2) NOT NULL,
     DAYS_RANGE_TO            NUMERIC(18,2) NOT NULL,
     NAME                     VARCHAR(100) NOT NULL,
     VOLUME                   NUMERIC(18,2) NOT NULL,
     STOCK_EXCHANGE           VARCHAR(18) NOT NULL,

     CONSTRAINT IPK_SNAPSHOT_QUOTE PRIMARY KEY (SQ_ID)
);

ALTER TABLE SNAPSHOT_QUOTE ADD CONSTRAINT IFK_SOURCE_CENTER_ENGINE_INSTANCE FOREIGN KEY (SCEI_ID) REFERENCES SOURCE_CENTER_ENGINE_INSTANCE (SCEI_ID);
ALTER TABLE SNAPSHOT_QUOTE ADD CONSTRAINT IFK_SYMBOL FOREIGN KEY (SYM_ID) REFERENCES SYMBOL (SYM_ID);
