CREATE TABLE SNAPSHOT_HISTORICAL (
    SH_ID           NUMERIC(18) NOT NULL DEFAULT nextval('S_SNAPSHOT_HISTORICAL_PK'),
    SCEI_ID         NUMERIC(18) NOT NULL,
    BUSINESS_DATE   DATE NOT NULL,
    SYM_ID          NUMERIC(18) NOT NULL,
    PERIOD          VARCHAR(10) NOT NULL,
    DATE            DATE NOT NULL,
    TIME            TIME NOT NULL,
    OPEN            NUMERIC(18) NOT NULL,
    HIGH            NUMERIC(18) NOT NULL,
    LOW             NUMERIC(18) NOT NULL,
    CLOSE           NUMERIC(18) NOT NULL,
    VOLUME          NUMERIC(18) NOT NULL,
    ACTIVE_FLAG     CHAR(1) DEFAULT 'Y' NOT NULL CHECK (ACTIVE_FLAG in ('Y','N') ),

    CONSTRAINT IPK_SNAPSHOT_HISTORICAL PRIMARY KEY (SCEI_ID)
);

ALTER TABLE SNAPSHOT_HISTORICAL ADD CONSTRAINT IFK_SOURCE_CENTER_ENGINE_INSTANCE FOREIGN KEY (SCEI_ID) REFERENCES SOURCE_CENTER_ENGINE_INSTANCE (SCEI_ID);
ALTER TABLE SNAPSHOT_HISTORICAL ADD CONSTRAINT IFK_SYMBOL FOREIGN KEY (SYM_ID) REFERENCES SYMBOL (SYM_ID);

