CREATE TABLE SNAPSHOT_FXRATE (
     SX_ID             NUMERIC(18) NOT NULL,
     SCEI_ID           NUMERIC(18) NOT NULL,
     SYM_ID            NUMERIC(18) NOT NULL
     BUSINESS_DATE     TIMESTAMP NOT NULL,
     ID                NUMERIC(18) NOT NULL,
     NAME              CHAR(18) NOT NULL,
     DATE              TIMESTAMP NOT NULL,
     TIME              TIMESTAMP NOT NULL,
     ASK               FLOAT NOT NULL,
     BID               FLOAT NOT NULL

     CONSTRAINT IPK_SNAPSHOT_FXRATE PRIMARY KEY (SX_ID) DEFAULT nextval('S_SNAPSHOT_FXRATE_PK')
    )TABLESPACE GENERAL_INDEX;

ALTER TABLE SNAPSHOT_FXRATE ADD CONSTRAINT IFK_STAGE_YAHOO_FXRATE FOREIGN KEY (SYM_ID) REFERENCES STAGE_YAHOO_FXRATE (SYM_ID) MATCH FULL;
ALTER TABLE SNAPSHOT_FXRATE ADD CONSTRAINT IFK_SOURCE_CENTER_ENGINE_INSATNCE FOREIGN KEY (SCEI_ID) REFERENCES SOURCE_CENTER_ENGINE_INSATNCE (SCEI_ID) MATCH FULL;
