CREATE TABLE SOURCE_CENTER_ENGINE_INSATNCE (
     SCEI_ID                    NUMERIC(18) NOT NULL,
     SCE_ID                     NUMERIC(18) NOT NULL,
     BUSINESS_DATE              TIMESTAMP NOT NULL,
     SCEI_STATE_CG_ID           NUMERIC(18) NOT NULL,
     SCEI_DETAIL_STATE_CG_ID    NUMERIC(18) NOT NULL,
     START_TM                   TIME NOT NULL,
     END_TM                     TIME NOT NULL,

     CONSTRAINT IPK_SOURCE_CENTER_ENGINE_INSTANCE PRIMARY KEY (SCEI_ID) DEFAULT nextval('S_SOURCE_CENTER_ENGINE_INSTANCE_PK')
) TABLESPACE GENERAL_INDEX;

ALTER TABLE SOURCE_CENTER_ENGINE_INSTANCE ADD CONSTRAINT IFK_SOURCE_CENTER_ENGINE FOREIGN KEY (SCE_ID) REFERENCES SOURCE_CENTER_ENGINE (SCE_ID) MATCH FULL;
ALTER TABLE SOURCE_CENTER_ENGINE_INSTANCE ADD CONSTRAINT IFK_CODE_GENERIC FOREIGN KEY (SCEI_STATE_CG_ID) REFERENCES CODE_GENERIC (CG_ID) MATCH FULL;
