CREATE TABLE SOURCE_CENTER(
     SC_ID                NUMERIC(18) NOT NULL DEFAULT nextval('S_SOURCE_CENTER_PK'),
     NAME                 VARCHAR(20) NOT NULL,
     DESCRIPTION          VARCHAR(40),
     LAST_UPDATE_TM       TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
     ACTIVE_FLAG          CHAR(1) DEFAULT 'Y' NOT NULL CHECK (ACTIVE_FLAG in ('Y','N') ),

       CONSTRAINT IPK_SOURCE_CENTER PRIMARY KEY (SC_ID)
);
