CREATE TABLE SOURCE_CENTER_ENGINE_INSTANCE (
     SCEI_ID                    NUMERIC(18) NOT NULL DEFAULT nextval('S_SOURCE_CENTER_ENGINE_INSTANCE_PK'),
     SCE_ID                     NUMERIC(18) NOT NULL,
     BUSINESS_DATE              DATE NOT NULL,
     SCEI_STATE_CG_ID           NUMERIC(18),
     SCEI_DETAIL_STATE_CG_ID    NUMERIC(18),
     START_TM                   TIMESTAMP,
     END_TM                     TIMESTAMP,

     CONSTRAINT IPK_SOURCE_CENTER_ENGINE_INSTANCE PRIMARY KEY (SCEI_ID)
);

ALTER TABLE SOURCE_CENTER_ENGINE_INSTANCE ADD CONSTRAINT IFK_SOURCE_CENTER_ENGINE FOREIGN KEY (SCE_ID) REFERENCES SOURCE_CENTER_ENGINE (SCE_ID);
ALTER TABLE SOURCE_CENTER_ENGINE_INSTANCE ADD CONSTRAINT IFK_CODE_GENERIC FOREIGN KEY (SCEI_STATE_CG_ID) REFERENCES CODE_GENERIC (CG_ID);
