CREATE TABLE SOURCE_CENTER(
     SC_ID                NUMERIC(18) NOT NULL,
     NAME                 VARCHAR(20) NOT NULL,
     DESCRIPTION          VARCHAR(40) NOT NULL,
     LAST_UPDATE_TM       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
     ACTIVE_FLAG          CHAR(1) DEFAULT 'Y' NOT NULL,

       CONSTRAINT IPK_SOURCE_CENTER PRIMARY KEY (SC_ID) DEFAULT nextval('S_SOURCE_CENTER_PK')
) TABLESPACE GENERAL_INDEX;

ALTER TABLE SOURCE_CENTER ADD ( CHECK (ACTIVE_FLAG in ('Y','N') );

