CREATE TABLE STAGE_YAHOO_HISTORICAL(
  SFH_ID            NUMERIC(18) NOT NULL,
  HASH              NUMERIC(18) NOT NULL,
  SYMBOL            VARCHAR(20) NOT NULL,
  SYM_ID            NUMERIC(18) NOT NULL,
  PER               NUMERIC(5) NOT NULL,
  DATE              DATETIME NOT NULL,
  TIME              DATETIME NOT NULL,
  OPEN              NUMERIC(18) NOT NULL,
  HIGH              NUMERIC(18) NOT NULL,
  LOW               NUMERIC(18) NOT NULL,
  CLOSE             NUMERIC(18) NOT NULL,
  VOLUME            NUMERIC(18) NOT NULL,
  ACTIVE_FLAG       CHAR(1) DEFAULT 'Y' NOT NULL,
  ACTIVE_REASON     CHAR(1) NOT NULL,

   CONSTRAINT IPK_STAGE_YAHOO_HISTORICAL PRIMARY KEY (SFH_ID) DEFAULT nextval('S_STAGE_YAHOO_HISTORICAL_PK')
) TABLESPACE GENERAL_INDEX;
