CREATE TABLE STAGE_YAHOO_FXRATE (
     HASH         NUMERIC(18),
     ID           VARCHAR(20) NOT NULL,
     NAME         VARCHAR(20) NOT NULL,
     RATE         NUMERIC(18),
     DATE         DATE NOT NULL,
     TIME         TIME NOT NULL,
     ASK          NUMERIC(18),
     BID          NUMERIC(18),
     SYM_ID       NUMERIC(18),
     ACTIVE_FLAG       CHAR(1) DEFAULT 'Y' NOT NULL CHECK (ACTIVE_FLAG in ('Y','N') ),
     ACTIVE_REASON     VARCHAR(20),

     CONSTRAINT IPK_STAGE_YAHOO_FXRATE PRIMARY KEY (ID, NAME, DATE, TIME, ACTIVE_FLAG)
);
