CREATE TABLE STAGE_YAHOO_HISTORICAL(
  SFH_ID            NUMERIC(18) NOT NULL,
  HASH              VARCHAR(20) NOT NULL,
  SYMBOL            VARCHAR(20) NOT NULL,
  SYM_ID            VARCHAR(20) NOT NULL,
  PER               VARCHAR(20) NOT NULL,
  DATE              DATETIME NOT NULL,
  TIME              DATETIME NOT NULL,
  OPEN              NUMERIC(18) NOT NULL,
  HIGH              NUMERIC(18) NOT NULL,
  LOW               NUMERIC(18) NOT NULL,
  CLOSE             VARCHAR(20) NOT NULL,
  VOLUME            VARCHAR(20) NOT NULL,
  ACTIVE_FLAG       VARCHAR(20) NOT NULL,
  ACTIVE_REASON     VARCHAR(20) NOT NULL,

   CONSTRAINT IPK_STAGE_YAHOO_HISTORICAL PRIMARY KEY (SFH_ID) DEFAULT nextval('S_STAGE_YAHOO_HISTORICAL_PK')
) TABLESPACE GENERAL_INDEX;
