CREATE TABLE SYMBOL_EXCHANGE (
    SYM_ID              NUMERIC(18) NOT NULL,
    EXCHANGE_ID         NUMERIC(18) NOT NULL,
    LAST_UPDATE_TM      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT IPK_SYMBOL_EXCHANGE PRIMARY KEY (SYM_ID, EXCHANGE_ID)

);

ALTER TABLE SYMBOL_EXCHANGE ADD CONSTRAINT IFK_SYMBOL FOREIGN KEY (SYM_ID) REFERENCES SYMBOL (SYM_ID);
ALTER TABLE SYMBOL_EXCHANGE ADD CONSTRAINT IFK_EXCHANGE FOREIGN KEY (EXCHANGE_ID) REFERENCES EXCHANGE (EX_ID);
