CREATE TABLE SYMBOL_EXCHANGE (
    SYM_ID              NUMERIC(18) NOT NULL,
    EXCHANGE_ID         NUMERIC(18) NOT NULL,
    LAST_UPDATE_TM      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT IPK_SYMBOL_EXCHANGE PRIMARY_KEY (SYM_ID, EXCHANGE_ID)

) TABLESPACE GENERAL_INDEX;

ALTER TABLE SYMBOL ADD CONSTRAINT IFK_SYMBOL FOREIGN KEY (SYM_ID) REFERENCES SYMBOL (SYM_ID) MATCH FULL;
ALTER TABLE SYMBOL ADD CONSTRAINT IFK_EXCHANGE FOREIGN KEY (EXCHANGE_ID) REFERENCES EXCHANGE (EX_ID) MATCH FULL;