CREATE TABLE SYMBOL (
    SYM_ID              NUMERIC(18) NOT NULL DEFAULT nextval('S_SYMBOL_PK'),
    NAME                VARCHAR(20) NOT NULL,
    DESCRIPTION         VARCHAR(40),
    ISIN                VARCHAR(12),
    MASTER_SYM_ID       NUMERIC(18),
    EX_ID               NUMERIC(18),
    LAST_UPDATE_TM      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT IPK_SYMBOL PRIMARY KEY (SYM_ID)

);

ALTER TABLE SYMBOL ADD CONSTRAINT IFK_SYMBOL FOREIGN KEY (MASTER_SYM_ID) REFERENCES SYMBOL (SYM_ID);
ALTER TABLE SYMBOL ADD CONSTRAINT IFK_EXCHANGE FOREIGN KEY (EX_ID) REFERENCES EXCHANGE (EX_ID);
