CREATE TABLE SYMBOL (
         SCE_ID             NUMERIC(18) NOT NULL,
         SC_ID              NUMERIC(18) NOT NULL,
         NAME               VARCHAR(20) NOT NULL,
         DESCRIPTION        VARCHAR(20) NOT NULL,
         MASTER_SYM_ID      NUMERIC(18) NOT NULL,
         EX_ID              NUMERIC(18) NOT NULL,
         LAST_UPDATE_TM     NUMERIC(18) NOT NULL,

         CONSTRAINT IPK_SOURCE_CENTER_ENGINE PRIMARY KEY (SC_ID) DEFAULT nextval('S_SOURCE_SYMBOL_PK')

) TABLESPACE GENERAL_INDEX;
CREATE UNIQUE INDEX IUK_SYMBOL_NAME ON SYMBOL (TYPE, NAME) TABLESPACE GENERAL_INDEX;
