//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.12 at 04:11:09 AM MSK 
//


package com.youtrack.view;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for assigneeList complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="assigneeList"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="assignees" type="{}assignees"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="groupsUrl" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="individualsUrl" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assigneeList", propOrder = {
        "assignees"
})
public class AssigneeList {

    @XmlElement(required = true)
    protected Assignees assignees;
    @XmlAttribute(name = "groupsUrl")
    protected String groupsUrl;
    @XmlAttribute(name = "individualsUrl")
    protected String individualsUrl;

    /**
     * Gets the value of the assignees property.
     *
     * @return possible object is
     * {@link Assignees }
     */
    public Assignees getAssignees() {
        return assignees;
    }

    /**
     * Sets the value of the assignees property.
     *
     * @param value allowed object is
     *              {@link Assignees }
     */
    public void setAssignees(Assignees value) {
        this.assignees = value;
    }

    /**
     * Gets the value of the groupsUrl property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getGroupsUrl() {
        return groupsUrl;
    }

    /**
     * Sets the value of the groupsUrl property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGroupsUrl(String value) {
        this.groupsUrl = value;
    }

    /**
     * Gets the value of the individualsUrl property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIndividualsUrl() {
        return individualsUrl;
    }

    /**
     * Sets the value of the individualsUrl property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIndividualsUrl(String value) {
        this.individualsUrl = value;
    }

}
