//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.12 at 04:11:09 AM MSK 
//


package com.youtrack.view;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for assignee complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="assignee"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="assignedBy" type="{}assignedByType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="login" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="isIndividualAssignee" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assignee", propOrder = {
        "assignedBy"
})
public class Assignee {

    @XmlElement(required = true)
    protected AssignedByType assignedBy;
    @XmlAttribute(name = "login")
    protected String login;
    @XmlAttribute(name = "isIndividualAssignee")
    protected String isIndividualAssignee;

    /**
     * Gets the value of the assignedBy property.
     *
     * @return possible object is
     * {@link AssignedByType }
     */
    public AssignedByType getAssignedBy() {
        return assignedBy;
    }

    /**
     * Sets the value of the assignedBy property.
     *
     * @param value allowed object is
     *              {@link AssignedByType }
     */
    public void setAssignedBy(AssignedByType value) {
        this.assignedBy = value;
    }

    /**
     * Gets the value of the login property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLogin(String value) {
        this.login = value;
    }

    /**
     * Gets the value of the isIndividualAssignee property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIsIndividualAssignee() {
        return isIndividualAssignee;
    }

    /**
     * Sets the value of the isIndividualAssignee property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIsIndividualAssignee(String value) {
        this.isIndividualAssignee = value;
    }

}
