//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.12 at 04:11:09 AM MSK 
//


package com.youtrack.view;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for issue complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="issue"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="field" type="{}field"/&gt;
 *         &lt;element name="comment" type="{}comment" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "issue", propOrder = {
        "fieldOrComment"
})
public class Issue {

    @XmlElements({
            @XmlElement(name = "field", type = Field.class),
            @XmlElement(name = "comment", type = Comment.class)
    })
    protected List<Object> fieldOrComment;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the fieldOrComment property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldOrComment property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldOrComment().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * {@link Comment }
     */
    public List<Object> getFieldOrComment() {
        if (fieldOrComment == null) {
            fieldOrComment = new ArrayList<Object>();
        }
        return this.fieldOrComment;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("Issue[\n");
        sb.append("  id=").append(id).append('\n');
        for (Object o : fieldOrComment) {
            sb.append("  ").append(o).append('\n');
        }
        sb.append(']');
        return sb.toString();
    }
}
