//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.12 at 04:11:09 AM MSK 
//


package com.youtrack.view;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.youtrack.view package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and view
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AssigneeList_QNAME = new QName("", "assigneeList");
    private final static QName _Issue_QNAME = new QName("", "issue");
    private final static QName _Project_QNAME = new QName("", "project");
    private final static QName _User_QNAME = new QName("", "user");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.youtrack.view
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AssigneeList }
     */
    public AssigneeList createAssigneeList() {
        return new AssigneeList();
    }

    /**
     * Create an instance of {@link Issue }
     */
    public Issue createIssue() {
        return new Issue();
    }

    /**
     * Create an instance of {@link Project }
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link User }
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link AssignedByType }
     */
    public AssignedByType createAssignedByType() {
        return new AssignedByType();
    }

    /**
     * Create an instance of {@link UserGroupRefType }
     */
    public UserGroupRefType createUserGroupRefType() {
        return new UserGroupRefType();
    }

    /**
     * Create an instance of {@link Assignee }
     */
    public Assignee createAssignee() {
        return new Assignee();
    }

    /**
     * Create an instance of {@link Assignees }
     */
    public Assignees createAssignees() {
        return new Assignees();
    }

    /**
     * Create an instance of {@link Value }
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link Comment }
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link Field }
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssigneeList }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "assigneeList")
    public JAXBElement<AssigneeList> createAssigneeList(AssigneeList value) {
        return new JAXBElement<AssigneeList>(_AssigneeList_QNAME, AssigneeList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Issue }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "issue")
    public JAXBElement<Issue> createIssue(Issue value) {
        return new JAXBElement<Issue>(_Issue_QNAME, Issue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Project }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "project")
    public JAXBElement<Project> createProject(Project value) {
        return new JAXBElement<Project>(_Project_QNAME, Project.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "user")
    public JAXBElement<User> createUser(User value) {
        return new JAXBElement<User>(_User_QNAME, User.class, null, value);
    }

}
