//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.12 at 04:11:09 AM MSK 
//


package com.youtrack.view;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for project complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="project"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="lead" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="assigneesUrl" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="subsystemsUrl" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="buildsUrl" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="versionsUrl" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="startingNumber" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "project", propOrder = {
        "value"
})
public class Project {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "lead")
    protected String lead;
    @XmlAttribute(name = "assigneesUrl")
    protected String assigneesUrl;
    @XmlAttribute(name = "subsystemsUrl")
    protected String subsystemsUrl;
    @XmlAttribute(name = "buildsUrl")
    protected String buildsUrl;
    @XmlAttribute(name = "versionsUrl")
    protected String versionsUrl;
    @XmlAttribute(name = "startingNumber")
    protected String startingNumber;

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the lead property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLead() {
        return lead;
    }

    /**
     * Sets the value of the lead property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLead(String value) {
        this.lead = value;
    }

    /**
     * Gets the value of the assigneesUrl property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAssigneesUrl() {
        return assigneesUrl;
    }

    /**
     * Sets the value of the assigneesUrl property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAssigneesUrl(String value) {
        this.assigneesUrl = value;
    }

    /**
     * Gets the value of the subsystemsUrl property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSubsystemsUrl() {
        return subsystemsUrl;
    }

    /**
     * Sets the value of the subsystemsUrl property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSubsystemsUrl(String value) {
        this.subsystemsUrl = value;
    }

    /**
     * Gets the value of the buildsUrl property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBuildsUrl() {
        return buildsUrl;
    }

    /**
     * Sets the value of the buildsUrl property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBuildsUrl(String value) {
        this.buildsUrl = value;
    }

    /**
     * Gets the value of the versionsUrl property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVersionsUrl() {
        return versionsUrl;
    }

    /**
     * Sets the value of the versionsUrl property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVersionsUrl(String value) {
        this.versionsUrl = value;
    }

    /**
     * Gets the value of the startingNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getStartingNumber() {
        return startingNumber;
    }

    /**
     * Sets the value of the startingNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setStartingNumber(String value) {
        this.startingNumber = value;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this, ToStringStyle.MULTI_LINE_STYLE)
                .append("id", id)
                .append("name", name)
                .append("lead", lead)
                .append("value", value)
                .append("assigneesUrl", assigneesUrl)
                .append("subsystemsUrl", subsystemsUrl)
                .append("buildsUrl", buildsUrl)
                .append("versionsUrl", versionsUrl)
                .append("startingNumber", startingNumber)
                .toString();
    }
}
