//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.12 at 04:11:09 AM MSK 
//


package com.youtrack.view;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for user complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="user"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="login" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="fullName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="lastAccess" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="groupsUrl" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="rolesUrl" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "user", propOrder = {
        "value"
})
public class User {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "login")
    protected String login;
    @XmlAttribute(name = "fullName")
    protected String fullName;
    @XmlAttribute(name = "lastAccess")
    protected String lastAccess;
    @XmlAttribute(name = "groupsUrl")
    protected String groupsUrl;
    @XmlAttribute(name = "rolesUrl")
    protected String rolesUrl;

    /**
     * Gets the value of the value property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the login property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLogin(String value) {
        this.login = value;
    }

    /**
     * Gets the value of the fullName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the lastAccess property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLastAccess() {
        return lastAccess;
    }

    /**
     * Sets the value of the lastAccess property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLastAccess(String value) {
        this.lastAccess = value;
    }

    /**
     * Gets the value of the groupsUrl property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getGroupsUrl() {
        return groupsUrl;
    }

    /**
     * Sets the value of the groupsUrl property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGroupsUrl(String value) {
        this.groupsUrl = value;
    }

    /**
     * Gets the value of the rolesUrl property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRolesUrl() {
        return rolesUrl;
    }

    /**
     * Sets the value of the rolesUrl property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRolesUrl(String value) {
        this.rolesUrl = value;
    }

}
