//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.22 at 07:39:05 PM MSK 
//


package com.sedc.collectors.finam.symbol.model;

import lombok.Data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="board" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="shortName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="priceStep" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="multiplier" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="decimals" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="currency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "security")
@Data
public class FinamJaxbSecurity {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "code")
    protected String code;
    @XmlAttribute(name = "board")
    protected String board;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "shortName")
    protected String shortName;
    @XmlAttribute(name = "priceStep")
    protected Float priceStep;
    @XmlAttribute(name = "multiplier")
    protected Integer multiplier;
    @XmlAttribute(name = "decimals")
    protected Byte decimals;
    @XmlAttribute(name = "currency")
    protected String currency;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "isin")
    protected String isin;

}
